version: '3.9'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/memory
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:16.0-alpine3.18
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=memory_dev
    redis:
        image: redis:7.2.2-alpine
        hostname: redis
    worker:
        build:
            context: .
        hostname: worker
        env_file:
            - ./.env.dev
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=memory_dev
        entrypoint: celery
        command: -A celery_app.app worker --loglevel=error
        volumes:
            - .:/usr/src/memory
        links:
            - redis
        depends_on:
            - redis
            - db
    flower:
        build:
            context: .
        hostname: flower
        env_file:
            - ./.env.dev
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=memory_dev
        entrypoint: celery
        command: -A celery_app.app flower
        volumes:
            - .:/usr/src/memory
        links:
            - redis
        depends_on:
            - redis
            - worker
            - db
        ports:
            - '5555:5555'

volumes:
    postgres_data: