# Generated by Django 4.2.6 on 2023-11-09 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_from', models.CharField(blank=True, max_length=150, verbose_name='От кого')),
                ('send_date', models.DateField(verbose_name='Дата отправки')),
                ('name_to', models.CharField(verbose_name='Кому')),
                ('address', models.CharField(verbose_name='Адрес получателя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email получателя')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
